./webapps/xwiki/resources/js/xwiki/panelwizard/Drag.js
./webapps/xwiki/resources/js/xwiki/panelwizard/Drag.min.js
./webapps/xwiki/resources/js/xwiki/panelwizard/toolTip.js
./webapps/xwiki/resources/js/xwiki/panelwizard/ieemu.min.js
./webapps/xwiki/resources/js/xwiki/panelwizard/ieemu.js
./webapps/xwiki/resources/js/xwiki/panelwizard/panelWizard.min.js
./webapps/xwiki/resources/js/xwiki/panelwizard/toolTip.min.js
./webapps/xwiki/resources/js/xwiki/panelwizard/panelWizard.js
./webapps/xwiki/resources/js/xwiki/usersandgroups/usersandgroups.min.js
./webapps/xwiki/resources/js/xwiki/usersandgroups/usersandgroups.js
./webapps/xwiki/resources/js/xwiki/markerScript.min.js
./webapps/xwiki/resources/js/xwiki/accordion/accordion.min.js
./webapps/xwiki/resources/js/xwiki/accordion/accordion.js
./webapps/xwiki/resources/js/xwiki/meta.js
./webapps/xwiki/resources/js/xwiki/create.js
./webapps/xwiki/resources/js/xwiki/eventsBridge.min.js
./webapps/xwiki/resources/js/xwiki/xwiki.min.js
./webapps/xwiki/resources/js/xwiki/actionbuttons/actionButtons.min.js
./webapps/xwiki/resources/js/xwiki/actionbuttons/actionButtons.js
./webapps/xwiki/resources/js/xwiki/xwiki.bundle.min.js
./webapps/xwiki/resources/js/xwiki/editors/dataeditors.js
./webapps/xwiki/resources/js/xwiki/editors/autosave.js
./webapps/xwiki/resources/js/xwiki/editors/dataeditors.min.js
./webapps/xwiki/resources/js/xwiki/editors/autosave.min.js
./webapps/xwiki/resources/js/xwiki/xwiki.js
./webapps/xwiki/resources/js/xwiki/compatibility.min.js
./webapps/xwiki/resources/js/xwiki/eventsBridge.js
./webapps/xwiki/resources/js/xwiki/viewers/information.min.js
./webapps/xwiki/resources/js/xwiki/viewers/attachments.min.js
./webapps/xwiki/resources/js/xwiki/viewers/attachments.js
./webapps/xwiki/resources/js/xwiki/viewers/information.js
./webapps/xwiki/resources/js/xwiki/compatibility.js
./webapps/xwiki/resources/js/xwiki/importer/import.min.js
./webapps/xwiki/resources/js/xwiki/importer/import.js
./webapps/xwiki/resources/js/xwiki/wikieditor/wikibits.js
./webapps/xwiki/resources/js/xwiki/wikieditor/wikibits.min.js
./webapps/xwiki/resources/js/xwiki/table/livetable.js
./webapps/xwiki/resources/js/xwiki/table/tablefilterNsort.min.js
./webapps/xwiki/resources/js/xwiki/table/livetablemulti.min.js
./webapps/xwiki/resources/js/xwiki/table/livetabledate.min.js
./webapps/xwiki/resources/js/xwiki/table/tablefilterNsort.js
./webapps/xwiki/resources/js/xwiki/table/livetabledate.js
./webapps/xwiki/resources/js/xwiki/table/livetablemulti.js
./webapps/xwiki/resources/js/xwiki/table/livetable.min.js
./webapps/xwiki/resources/js/xwiki/markerScript.js
./webapps/xwiki/resources/js/xwiki/create.min.js
./webapps/xwiki/resources/js/xwiki/widgets/jumpToPage.min.js
./webapps/xwiki/resources/js/xwiki/widgets/modalPopup.js
./webapps/xwiki/resources/js/xwiki/widgets/jumpToPage.js
./webapps/xwiki/resources/js/xwiki/widgets/modalPopup.min.js
./webapps/xwiki/resources/js/xwiki/meta.min.js
./webapps/xwiki/resources/js/prototype/prototype.min.js
./webapps/xwiki/resources/js/prototype/prototype.js
./webapps/xwiki/resources/js/scriptaculous/dragdrop.js
./webapps/xwiki/resources/js/scriptaculous/effects.min.js
./webapps/xwiki/resources/js/scriptaculous/effects.js
./webapps/xwiki/resources/js/scriptaculous/dragdrop.min.js
./webapps/xwiki/resources/uicomponents/flavor/picker.js
./webapps/xwiki/resources/uicomponents/flavor/picker.min.js
./webapps/xwiki/resources/uicomponents/logging/logging.min.js
./webapps/xwiki/resources/uicomponents/logging/logging.js
./webapps/xwiki/resources/uicomponents/edit/editableProperty.js
./webapps/xwiki/resources/uicomponents/edit/editableProperty.min.js
./webapps/xwiki/resources/uicomponents/model/entityReference.js
./webapps/xwiki/resources/uicomponents/model/entityReference.min.js
./webapps/xwiki/resources/uicomponents/lock/lock.js
./webapps/xwiki/resources/uicomponents/lock/lock.min.js
./webapps/xwiki/resources/uicomponents/require/deferred.min.js
./webapps/xwiki/resources/uicomponents/require/deferred.js
./webapps/xwiki/resources/uicomponents/debug/debug.min.js
./webapps/xwiki/resources/uicomponents/debug/debug.js
./webapps/xwiki/resources/uicomponents/dashboard/dashboard.min.js
./webapps/xwiki/resources/uicomponents/dashboard/gadgetWizard.min.js
./webapps/xwiki/resources/uicomponents/dashboard/gadgetWizard.js
./webapps/xwiki/resources/uicomponents/dashboard/dashboard.js
./webapps/xwiki/resources/uicomponents/hierarchy/hierarchy.min.js
./webapps/xwiki/resources/uicomponents/hierarchy/hierarchy.js
./webapps/xwiki/resources/uicomponents/viewers/tags.min.js
./webapps/xwiki/resources/uicomponents/viewers/history.min.js
./webapps/xwiki/resources/uicomponents/viewers/tags.js
./webapps/xwiki/resources/uicomponents/viewers/comments.min.js
./webapps/xwiki/resources/uicomponents/viewers/diff.js
./webapps/xwiki/resources/uicomponents/viewers/diff.min.js
./webapps/xwiki/resources/uicomponents/viewers/comments.js
./webapps/xwiki/resources/uicomponents/viewers/history.js
./webapps/xwiki/resources/uicomponents/extension/clean.js
./webapps/xwiki/resources/uicomponents/extension/history.min.js
./webapps/xwiki/resources/uicomponents/extension/clean.min.js
./webapps/xwiki/resources/uicomponents/extension/extension.min.js
./webapps/xwiki/resources/uicomponents/extension/distribution.js
./webapps/xwiki/resources/uicomponents/extension/extension.js
./webapps/xwiki/resources/uicomponents/extension/distribution.min.js
./webapps/xwiki/resources/uicomponents/extension/history.js
./webapps/xwiki/resources/uicomponents/job/question/XClassBreakingQuestion.js
./webapps/xwiki/resources/uicomponents/job/question/ExtensionBreakingQuestion.min.js
./webapps/xwiki/resources/uicomponents/job/question/XClassBreakingQuestion.min.js
./webapps/xwiki/resources/uicomponents/job/question/ExtensionBreakingQuestion.js
./webapps/xwiki/resources/uicomponents/job/job.js
./webapps/xwiki/resources/uicomponents/job/job.min.js
./webapps/xwiki/resources/uicomponents/async/async.js
./webapps/xwiki/resources/uicomponents/async/async.min.js
./webapps/xwiki/resources/uicomponents/search/searchSuggest.min.js
./webapps/xwiki/resources/uicomponents/search/searchSuggest.js
./webapps/xwiki/resources/uicomponents/exporter/exporter.js
./webapps/xwiki/resources/uicomponents/exporter/exporter.min.js
./webapps/xwiki/resources/uicomponents/widgets/tree.js
./webapps/xwiki/resources/uicomponents/widgets/upload.js
./webapps/xwiki/resources/uicomponents/widgets/notification.js
./webapps/xwiki/resources/uicomponents/widgets/liveData.js
./webapps/xwiki/resources/uicomponents/widgets/buttonGroup.min.js
./webapps/xwiki/resources/uicomponents/widgets/fullScreen.min.js
./webapps/xwiki/resources/uicomponents/widgets/tree.min.js
./webapps/xwiki/resources/uicomponents/widgets/locationPicker.js
./webapps/xwiki/resources/uicomponents/widgets/list/xlist.min.js
./webapps/xwiki/resources/uicomponents/widgets/list/xlist.js
./webapps/xwiki/resources/uicomponents/widgets/confirmedAjaxRequest.js
./webapps/xwiki/resources/uicomponents/widgets/fullScreen.js
./webapps/xwiki/resources/uicomponents/widgets/select/select.min.js
./webapps/xwiki/resources/uicomponents/widgets/select/select.js
./webapps/xwiki/resources/uicomponents/widgets/confirmationBox.js
./webapps/xwiki/resources/uicomponents/widgets/upload.min.js
./webapps/xwiki/resources/uicomponents/widgets/liveData.min.js
./webapps/xwiki/resources/uicomponents/widgets/locationPicker.min.js
./webapps/xwiki/resources/uicomponents/widgets/validation/livevalidation_prototype.js
./webapps/xwiki/resources/uicomponents/widgets/validation/livevalidation_prototype.min.js
./webapps/xwiki/resources/uicomponents/widgets/confirmationBox.min.js
./webapps/xwiki/resources/uicomponents/widgets/confirmedAjaxRequest.min.js
./webapps/xwiki/resources/uicomponents/widgets/buttonGroup.js
./webapps/xwiki/resources/uicomponents/widgets/gallery/gallery.js
./webapps/xwiki/resources/uicomponents/widgets/gallery/gallery.min.js
./webapps/xwiki/resources/uicomponents/widgets/notification.min.js
./webapps/xwiki/resources/uicomponents/suggest/xwiki.selectize.min.js
./webapps/xwiki/resources/uicomponents/suggest/suggestUsersAndGroups.js
./webapps/xwiki/resources/uicomponents/suggest/suggestPropertyValues.js
./webapps/xwiki/resources/uicomponents/suggest/suggestEntities.min.js
./webapps/xwiki/resources/uicomponents/suggest/suggestUsersAndGroups.min.js
./webapps/xwiki/resources/uicomponents/suggest/xwiki.selectize.js
./webapps/xwiki/resources/uicomponents/suggest/suggestEntities.js
./webapps/xwiki/resources/uicomponents/suggest/suggestPages.min.js
./webapps/xwiki/resources/uicomponents/suggest/suggestPropertyValues.min.js
./webapps/xwiki/resources/uicomponents/suggest/suggestPages.js
./webapps/xwiki/resources/uicomponents/suggest/suggestAttachments.js
./webapps/xwiki/resources/uicomponents/suggest/suggest.js
./webapps/xwiki/resources/uicomponents/suggest/suggest.min.js
./webapps/xwiki/resources/uicomponents/suggest/suggestAttachments.min.js
./webapps/xwiki/skins/flamingo/localePicker.min.js
./webapps/xwiki/skins/flamingo/flamingo.js
./webapps/xwiki/skins/flamingo/dateTimePicker.js
./webapps/xwiki/skins/flamingo/flamingo.min.js
./webapps/xwiki/skins/flamingo/localePicker.js
./webapps/xwiki/skins/flamingo/colorPicker.min.js
./webapps/xwiki/skins/flamingo/syntaxPicker.min.js
./webapps/xwiki/skins/flamingo/syntaxPicker.js
./webapps/xwiki/skins/flamingo/dateTimePicker.min.js
./webapps/xwiki/skins/flamingo/colorPicker.js
./data/store/solr/search/conf/update-script.js
